development:
  adapter: postgresql
  encoding: unicode
  database: fisioapp_development
  pool: 5
  host: <%= Figaro.env.host %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  url: <%= Figaro.env.DATABASE_URL %>

test:
  adapter: postgresql
  encoding: unicode
  database: fisioapp_test
  pool: 5
  host: <%= Figaro.env.host %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  url: <%= Figaro.env.DATABASE_URL %>

production:
  adapter: postgresql
  encoding: unicode
  database: fisioapp
  pool: 5
  host: <%= Figaro.env.host %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>
  url: <%= Figaro.env.DATABASE_URL %>
